In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [2]:
data = pd.read_csv("final_data.csv")

In [3]:
data.head()

Unnamed: 0  Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0           0   0            5.1           3.5            1.4           0.2   
1           1   1            4.7           3.2            1.6           0.2   
2           2   2            4.9           3.1            1.5           0.1   
3           3   3            4.4           2.9            1.4           0.2   
4           4   4            5.0           3.4            1.5           0.2   

       Species  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [4]:
data.drop(["Unnamed: 0", "Id"], axis=1, inplace=True)

In [5]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.7           3.2            1.6           0.2  Iris-setosa
2            4.9           3.1            1.5           0.1  Iris-setosa
3            4.4           2.9            1.4           0.2  Iris-setosa
4            5.0           3.4            1.5           0.2  Iris-setosa

### Label Encoding

In [7]:
le = LabelEncoder()

In [9]:
data["Species"] = le.fit_transform(data["Species"])

In [10]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.7           3.2            1.6           0.2        0
2            4.9           3.1            1.5           0.1        0
3            4.4           2.9            1.4           0.2        0
4            5.0           3.4            1.5           0.2        0

### Veri Kontrol

In [11]:
data.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [12]:
data.dtypes

SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species            int32
dtype: object

### Train_Test_Split

In [13]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:,:-1], data.iloc[:,-1], test_size=0.2)

In [28]:
y_train.value_counts()

1    43
2    42
0    38
Name: Species, dtype: int64

In [29]:
y_test.value_counts()

2    12
1    10
0     9
Name: Species, dtype: int64

### Modelin Oluşturulması

In [31]:
import xgboost as xgb

In [34]:
xgb_cls = xgb.XGBClassifier(objective="multiclass:softmax", num_class=3)

In [35]:
xgb_cls.fit(X_train, y_train)

C:\Users\hpp\Anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[23:42:34] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
       gamma=0, gpu_id=-1, importance_type=None,
       interaction_constraints='', learning_rate=0.300000012,
       max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
       monotone_constraints='()', n_estimators=100, n_jobs=4, num_class=3,
       num_parallel_tree=1, objective='multi:softprob', predictor='auto',
       random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
       subsample=1, tree_method='exact', use_label_encoder=True,
       validate_parameters=1, verbosity=None)

In [37]:
preds = xgb_cls.predict(X_test)

In [38]:
preds

array([2, 0, 2, 1, 1, 2, 1, 2, 0, 1, 0, 1, 1, 2, 2, 0, 2, 0, 1, 1, 1, 0,
       0, 2, 1, 2, 1, 1, 0, 0, 2])

In [39]:
import numpy as np

In [40]:
np.array(y_test)

array([2, 0, 2, 2, 2, 2, 1, 2, 0, 1, 0, 1, 1, 2, 2, 0, 2, 0, 1, 1, 1, 0,
       0, 2, 1, 2, 1, 1, 0, 0, 2])

In [41]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [42]:
accuracy_score(y_test,preds)

0.9354838709677419

In [43]:
confusion_matrix(y_test, preds)

array([[ 9,  0,  0],
       [ 0, 10,  0],
       [ 0,  2, 10]], dtype=int64)